CUDA_VISIBLE_DEVICES=0,1,2,3
python -m torch.distributed.launch --nproc_per_node=4 --master_port 10383 --use_env train_DFOLD_dynamics.py \
experiment.num_gpus=4 \
experiment.batch_size=4 \
experiment.noise_scale=1.0 \
model.cfg_drop_rate=0.0 \
data.random_sample_train=True \
data.keep_first=100000 \
data.fix_sample_start=100000 \
experiment.ckpt_freq=400 \
experiment.num_epoch=500000 \
experiment.base_root=../DFOLDv2_res/result_v2_selfdata \
data.csv_path=train.csv \
data.val_csv_path=train.csv \
experiment.name=force_full_gen_10_release \
data.frame_time=2 \
data.frame_sample_step=1 \
experiment.separate_rot_loss=False \
experiment.trans_loss_weight=100.0 \
experiment.rot_loss_t_threshold=0.0 \
experiment.rot_loss_weight=7.0 \
experiment.torsion_loss_weight=1.0 \
model.ipa.temporal=False \
diffuser.r3.coordinate_scaling=1.0 \
experiment.log_freq=32
